/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nc7.javaproject;

public class App {
    public static void main(String[] args) {
        System.out.println("영화 A 관객 선호도 조사");
        System.out.println("----------------------------------");

        int participantNumber = 100;
        String participantName = "홍길동";
        int participantAge = 20;
        boolean movieAttendance = true;
        char gender = 'M';
        int movieRating = 4;

        System.out.printf("참여자 번호: %d\n", participantNumber);
        System.out.printf("참여자 이름: %s\n", participantName);
        System.out.printf("참여자 나이: %d\n", participantAge);
        System.out.printf("영화 A 관람 여부: %b\n", movieAttendance);
        System.out.printf("참여자 성별(M: 남자, W: 여자): %c\n", gender);
        System.out.printf("영화 A에 대한 평가(1-5): %d\n", movieRating);
    }
}


