/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nc7.javaproject;

public class App {
    public static void main(String[] args) {
      System.out.println("영화 A 관객 선호도 조사");
      System.out.println("----------------------------------");
  
      System.out.print("참여자 번호: ");
      System.out.println(100);
  
      System.out.printf("참여자 이름: %s", "홍길동");
      System.out.println();
  
      System.out.println("참여자 나이: " + 20);
  
      System.out.printf("영화 A 관람 여부: %b\n", true);
  
      System.out.printf("참여자 성별(M: 남자, W: 여자): %c\n", 'M');
  
      System.out.printf("영화 A에 대한 평가(1-5): %d\n", 4);
    }
  }

